#!/usr/bin/env bash
# change nginx to run as user nginx

chmod 777 /etc/nginx/nginx.conf
pkill apache2
sudo sed -i -e 's/user www-data/user nginx/' /etc/nginx/nginx.conf
sed -i 's/80/8080/g' /etc/nginx/sites-enabled/default
sudo -u nginx service nginx restart
